using ProjectManager.Application.Common.Interfaces;

namespace ProjectManager.Application.Devices.Queries.GetDevice;

public class EngineDto : IDeviceParam
{
    public int Id { get; set; }
    public DateTime TimeStamp { get; set; }
    public float Parametr1 { get; set; }
    public float Parametr2 { get; set; }
    public float Parametr3 { get; set; }
    public float Parametr4 { get; set; }
    public float Parametr5 { get; set; }
    public float Parametr6 { get; set; }
    public float Parametr7 { get; set; }
    public float Parametr8 { get; set; }
    public float Parametr9 { get; set; }
    public float Parametr10 { get; set; }
    public float Parametr11 { get; set; }
    public float Parametr12 { get; set; }
    public float Parametr13 { get; set; }
    public float Parametr14 { get; set; }
    public float Parametr15 { get; set; }
    public float Parametr16 { get; set; }
    public float Parametr17 { get; set; }
    public float Parametr18 { get; set; }
    public float Parametr19 { get; set; }
    public float Parametr20 { get; set; }
    public float Parametr21 { get; set; }
    public float Parametr22 { get; set; }
    public float Parametr23 { get; set; }
    public float Parametr24 { get; set; }
    public float Parametr25 { get; set; }
    public float Parametr26 { get; set; }
    public float Parametr27 { get; set; }
    public float Parametr28 { get; set; }
    public float Parametr29 { get; set; }
    public float Parametr30 { get; set; }
    public float Parametr31 { get; set; }
    public float Parametr32 { get; set; }
    public float Parametr33 { get; set; }
    public float Parametr34 { get; set; }
    public float Parametr35 { get; set; }
    public float Parametr36 { get; set; }
    public float Parametr37 { get; set; }
    public float Parametr38 { get; set; }
    public float Parametr39 { get; set; }
    public float Parametr40 { get; set; }
    public float Parametr41 { get; set; }
    public float Parametr42 { get; set; }
    public float Parametr43 { get; set; }
    public float Parametr44 { get; set; }
    public float Parametr45 { get; set; }
    public float Parametr46 { get; set; }
    public float Parametr47 { get; set; }
    public float Parametr48 { get; set; }
    public float Parametr49 { get; set; }
    public float Parametr50 { get; set; }
    public float Parametr51 { get; set; }
    public float Parametr52 { get; set; }
    public float Parametr53 { get; set; }
    public float Parametr54 { get; set; }
    public float Parametr55 { get; set; }
    public float Parametr56 { get; set; }
    public float Parametr57 { get; set; }
    public float Parametr58 { get; set; }
    public float Parametr59 { get; set; }
    public float Parametr60 { get; set; }
    public float Parametr61 { get; set; }
    public float Parametr62 { get; set; }
    public float Parametr63 { get; set; }
    public float Parametr64 { get; set; }
    public float Parametr65 { get; set; }
    public float Parametr66 { get; set; }
    public float Parametr67 { get; set; }
    public float Parametr68 { get; set; }
    public float Parametr69 { get; set; }
    public float Parametr70 { get; set; }
    public float Parametr71 { get; set; }
    public float Parametr72 { get; set; }
    public float Parametr73 { get; set; }
    public float Parametr74 { get; set; }
    public float Parametr75 { get; set; }
    public float Parametr76 { get; set; }
    public float Parametr77 { get; set; }
    public float Parametr78 { get; set; }
    public float Parametr79 { get; set; }
    public float Parametr80 { get; set; }
    public float Parametr81 { get; set; }
    public float Parametr82 { get; set; }
    public float Parametr83 { get; set; }
    public float Parametr84 { get; set; }
    public float Parametr85 { get; set; }
    public float Parametr86 { get; set; }
    public float Parametr87 { get; set; }
    public float Parametr88 { get; set; }
    public float Parametr89 { get; set; }
    public float Parametr90 { get; set; }
    public float Parametr91 { get; set; }
    public float Parametr92 { get; set; }
    public float Parametr93 { get; set; }
    public float Parametr94 { get; set; }
    public float Parametr95 { get; set; }
    public float Parametr96 { get; set; }
    public float Parametr97 { get; set; }
    public float Parametr98 { get; set; }
    public float Parametr99 { get; set; }
    public float Parametr100 { get; set; }
    public float Parametr101 { get; set; }
    public float Parametr102 { get; set; }
    public float Parametr103 { get; set; }
    public float Parametr104 { get; set; }
    public float Parametr105 { get; set; }
    public float Parametr106 { get; set; }
    public float Parametr107 { get; set; }
    public float Parametr108 { get; set; }
    public float Parametr109 { get; set; }
    public float Parametr110 { get; set; }
    public float Parametr111 { get; set; }
    public float Parametr112 { get; set; }
    public float Parametr113 { get; set; }
    public float Parametr114 { get; set; }
    public float Parametr115 { get; set; }
    public float Parametr116 { get; set; }
    public float Parametr117 { get; set; }
    public float Parametr118 { get; set; }
    public float Parametr119 { get; set; }
    public float Parametr120 { get; set; }
}
